/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { BLOCK_STATUS } from '@google-psat/common';
import { InfoType, TableColumn, TableData } from '../useTable';

export const tableSearchKeys = ['parsedCookie.name', 'parsedCookie.domain'];

export const tableFilters = {
  'analytics.category': {
    title: 'Category',
    hasStaticFilterValues: true,
    hasPrecalculatedFilterValues: true,
    filterValues: {
      Analytics: {
        selected: null,
      },
      Functional: {
        selected: null,
      },
      Marketing: {
        selected: null,
      },
      Uncategorized: {
        selected: null,
      },
    },
    sortValues: true,
    useGenericPersistenceKey: true,
  },
  isFirstParty: {
    title: 'Scope',
    hasStaticFilterValues: true,
    hasPrecalculatedFilterValues: true,
    filterValues: {
      'First Party': {
        selected: null,
      },
      'Third Party': {
        selected: null,
      },
    },
    useGenericPersistenceKey: true,
  },
  'parsedCookie.domain': {
    title: 'Domain',
  },
  'parsedCookie.httponly': {
    title: 'HttpOnly',
    hasStaticFilterValues: true,
    filterValues: {
      True: {
        selected: false,
      },
      False: {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  'parsedCookie.samesite': {
    title: 'SameSite',
    hasStaticFilterValues: true,
    filterValues: {
      None: {
        selected: false,
      },
      Lax: {
        selected: false,
      },
      Strict: {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  'parsedCookie.secure': {
    title: 'Secure',
    hasStaticFilterValues: true,
    filterValues: {
      True: {
        selected: false,
      },
      False: {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  'parsedCookie.path': {
    title: 'Path',
  },
  'parsedCookie.expires': {
    title: 'Retention Period',
    hasStaticFilterValues: true,
    filterValues: {
      Session: {
        selected: false,
      },
      'Short Term (<24h)': {
        selected: false,
      },
      'Medium Term (24h - 1 week)': {
        selected: false,
      },
      'Long Term (1 week - 1 month)': {
        selected: false,
      },
      'Extended Term (>1 month)': {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  'analytics.platform': {
    title: 'Platform',
    hasStaticFilterValues: true,
    hasPrecalculatedFilterValues: true,
    filterValues: {
      'Google Ads': {
        selected: null,
      },
      Google: {
        selected: null,
      },
      Unknown: {
        selected: null,
      },
      Gemius: {
        selected: null,
      },
      'Google Analytics': {
        selected: null,
      },
      Cookiebot: {
        selected: null,
      },
      Marfeel: {
        selected: null,
      },
      Lotame: {
        selected: null,
      },
      'DoubleClick/Google Marketing': {
        selected: null,
      },
      'Google AdSense': {
        selected: null,
      },
      Adform: {
        selected: null,
      },
      Smartadserver: {
        selected: null,
      },
      'ASP.net': {
        selected: null,
      },
    },
    sortValues: true,
    useGenericPersistenceKey: true,
  },
  blockedReasons: {
    title: 'Blocked Reasons',
    hasStaticFilterValues: true,
    hasPrecalculatedFilterValues: true,
    enableSelectAllOption: true,
    isSelectAllOptionSelected: false,
    filterValues: {
      SameSiteLax: {
        selected: null,
      },
      DomainMismatch: {
        selected: null,
      },
      SameSiteUnspecifiedTreatedAsLax: {
        selected: null,
      },
      ThirdPartyPhaseout: {
        selected: null,
      },
      UserPreferences: {
        selected: null,
      },
    },
    sortValues: true,
    useGenericPersistenceKey: true,
  },
  'parsedCookie.partitionKey': {
    title: 'Partition Key',
    hasStaticFilterValues: true,
    filterValues: {
      Set: {
        selected: false,
      },
      'Not Set': {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  headerType: {
    title: 'Set Via',
    hasStaticFilterValues: true,
    filterValues: {
      HTTP: {
        selected: false,
      },
      JS: {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  'parsedCookie.priority': {
    title: 'Priority',
    hasStaticFilterValues: true,
    filterValues: {
      Low: {
        selected: false,
      },
      Medium: {
        selected: false,
      },
      High: {
        selected: false,
      },
    },
    useGenericPersistenceKey: true,
  },
  exemptionReason: {
    title: 'Exemption Reasons',
    hasStaticFilterValues: true,
    hasPrecalculatedFilterValues: true,
    enableSelectAllOption: true,
    isSelectAllOptionSelected: false,
    filterValues: {},
    useGenericPersistenceKey: true,
  },
};

export const tableColumns: TableColumn[] = [
  {
    header: 'Name',
    accessorKey: 'parsedCookie.name',
    cell: (info: InfoType) => info,
    enableHiding: false,
    enableBodyCellPrefixIcon: true,
  },
  {
    header: 'Scope',
    accessorKey: 'isFirstParty',
    cell: (info: InfoType) => (!info ? 'Third Party' : 'First Party'),
  },
  {
    header: 'Domain',
    accessorKey: 'parsedCookie.domain',
    cell: (info: InfoType) => info,
  },
  {
    header: 'Partition Key',
    accessorKey: 'parsedCookie.partitionKey',
    cell: (info: InfoType) => info,
    initialWidth: 80,
  },
  {
    header: 'SameSite',
    accessorKey: 'parsedCookie.samesite',
    cell: (info: InfoType) => (info?.toString() || '').toLowerCase(),
  },
  {
    header: 'Category',
    accessorKey: 'analytics.category',
    cell: (info: InfoType) => (info as string).toLowerCase() || 'uncategorized',
  },
  {
    header: 'Platform',
    accessorKey: 'analytics.platform',
    cell: (info: InfoType) => (info ? info : 'Unknown'),
  },
  {
    header: 'HttpOnly',
    accessorKey: 'parsedCookie.httponly',
    cell: (info: InfoType) => (
      <p className="flex justify-center items-center">
        {info ? <span className="font-serif">✓</span> : ''}
      </p>
    ),
    initialWidth: 50,
  },
  {
    header: 'Secure',
    accessorKey: 'parsedCookie.secure',
    cell: (info: InfoType) => (
      <p className="flex justify-center items-center">
        {info ? <span className="font-serif">✓</span> : ''}
      </p>
    ),
    initialWidth: 50,
  },
  {
    header: 'Value',
    accessorKey: 'parsedCookie.value',
    cell: (info: InfoType) => info,
  },
  {
    header: 'Path',
    accessorKey: 'parsedCookie.path',
    cell: (info: InfoType) => info,
  },
  {
    header: 'Expires',
    accessorKey: 'parsedCookie.expires',
    cell: (info: InfoType) => (info === 'Session' || !info ? 'Session' : info),
  },
];

export const mockData: TableData[] = [
  {
    isBlocked: true,
    parsedCookie: {
      domain: '.google.com',
      expires: '2025-10-14T08:35:02.319Z',
      httponly: true,
      name: 'AEC',
      path: '/',
      priority: 'Medium',
      samesite: 'Lax',
      secure: true,
      size: 61,
      value: 'AVcja2e0PrqQm6HBnwsBWYGFysEt0EA8klT6fEij1ffklzDJbMsMrSpqLA',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['SameSiteLax'],
    analytics: {
      platform: 'Google Ads',
      category: 'Functional',
      name: 'AEC',
      domain: 'google.com',
      description: 'OCD_AEC_description',
      retention: 'OCD_retention_6_months',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: false,
    frameIdList: [
      '87861506DC8EBE88380B03936A41F211',
      '2AFB398F6B7700317E7DF90AA5997E4C',
    ],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: '.google.com',
      expires: '2026-05-17T08:35:04.527Z',
      httponly: false,
      name: 'SOCS',
      path: '/',
      priority: 'Medium',
      samesite: 'Lax',
      secure: true,
      size: 58,
      value: 'CAISHAgCEhJnd3NfMjAyNTA0MTQtMF9SQzIaAnBsIAEaBgiAiYHABg',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['SameSiteLax'],
    analytics: {
      platform: 'Google',
      category: 'Functional',
      name: 'SOCS',
      domain: 'google.com',
      description: 'OCD_SOCS_description',
      retention: 'OCD_retention_13_months',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: false,
    frameIdList: [
      '87861506DC8EBE88380B03936A41F211',
      '2AFB398F6B7700317E7DF90AA5997E4C',
    ],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: 'www.google.com',
      expires: '2025-04-17T08:45:04.000Z',
      httponly: false,
      name: 'DV',
      path: '/',
      priority: 'Medium',
      samesite: 'lax',
      secure: false,
      size: 33,
      value: 'M6g7TFJgCIIUQIaWaSHSPtAj4TEuZBk',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['DomainMismatch', 'SameSiteUnspecifiedTreatedAsLax'],
    analytics: {
      platform: 'Google',
      category: 'Marketing',
      name: 'DV',
      domain: 'google.com',
      description: 'OCD_DV_description',
      retention: 'OCD_retention_1_year',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: false,
    frameIdList: [
      '87861506DC8EBE88380B03936A41F211',
      '2AFB398F6B7700317E7DF90AA5997E4C',
    ],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: ['WarnSameSiteUnspecifiedCrossSiteContext'],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: '.google.com',
      expires: '2026-05-18T00:53:20.788Z',
      httponly: true,
      name: 'NID',
      path: '/',
      priority: 'Medium',
      samesite: 'None',
      secure: true,
      size: 315,
      value: '',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['ThirdPartyPhaseout'],
    analytics: {
      platform: 'Google',
      category: 'Marketing',
      name: 'NID',
      domain: 'google.com',
      description: 'OCD_NID_description',
      retention: 'OCD_retention_1_year',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: false,
    frameIdList: [
      '87861506DC8EBE88380B03936A41F211',
      '2AFB398F6B7700317E7DF90AA5997E4C',
    ],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: '.tools.national-geographic.pl',
      expires: '2026-05-17T08:35:45.549Z',
      httponly: false,
      name: 'GAD',
      path: '/',
      priority: 'Medium',
      samesite: 'None',
      secure: true,
      size: 103,
      value:
        'KlSdVRGGQMQGGQ_27ju7QlGvssGML1AaL6PxGsRP5M7xcMSSSTAGpRgBtcvSGaG16njnE8QpERTsSLQ8RgNSDJFZxmS8MXP1sG..',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['DomainMismatch'],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: 'www.national-geographic.pl',
      expires: '2025-04-17T09:05:45.675Z',
      httponly: false,
      name: 'lux_uid',
      path: '/',
      priority: 'Medium',
      samesite: 'Lax',
      secure: false,
      size: 25,
      value: '174487890715829992',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['DomainMismatch'],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-05-17T08:35:07.000Z',
      httponly: false,
      name: '__gfp_64b',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 77,
      value:
        '6HEapC5AanGH9gak29UU6BEDtngJeF7VIhsdl1FF.oX.z7|1744878907|2|||8:2:32',
      partitionKey: '',
      samesite: 'lax',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Gemius',
      category: 'Analytics',
      name: '__gfp_64b',
      domain: '.gemius.pl',
      description: 'OCD___gfp_64b_description',
      retention: 'OCD_retention_13_months',
      dataController: 'Gemius',
      gdprUrl: 'https://www.gemius.pl/privacy-notice-for-panelists.html',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: 'www.national-geographic.pl',
      expires: '2026-05-22T08:35:46.516Z',
      httponly: false,
      name: 'GN_USER_ID_KEY',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 50,
      value: '33fb9647-e621-4429-8630-bb157deb7a98',
      partitionKey: '',
      samesite: 'lax',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['DomainMismatch'],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: true,
    parsedCookie: {
      domain: 'www.national-geographic.pl',
      expires: '2025-04-17T09:05:46.000Z',
      httponly: false,
      name: 'GN_SESSION_ID_KEY',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 53,
      value: 'e3b6fa3d-6b6b-4aff-bc36-76fd941b074e',
      partitionKey: '',
      samesite: 'lax',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: ['DomainMismatch'],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.BLOCKED_IN_ALL_EVENTS,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-05-22T08:35:46.632Z',
      httponly: false,
      name: '_ga',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 29,
      value: 'GA1.1.872992345.1744878908',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Google Analytics',
      category: 'Analytics',
      name: '_ga',
      domain: '',
      description: 'OCD__ga_description',
      retention: 'OCD_retention_2_years',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-04-17T08:35:08.000Z',
      httponly: false,
      name: '__ca__chat',
      path: '/',
      priority: 'Medium',
      secure: true,
      size: 22,
      value: '2f1emtczfaws',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2025-07-16T08:35:09.604Z',
      httponly: false,
      name: 'consentUUID',
      path: '/',
      priority: 'Medium',
      secure: true,
      size: 50,
      value: 'cec48b10-79e1-470d-9348-f6d36dade5c6_43',
      samesite: 'none',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Cookiebot',
      category: 'Functional',
      name: 'consentUUID',
      domain: '',
      description: 'OCD_consentUUID_description',
      retention: 'OCD_retention_1_year',
      dataController: 'Cookiebot',
      gdprUrl: 'https://www.cookiebot.com/en/cookie-declaration/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2025-07-16T08:35:09.604Z',
      httponly: false,
      name: 'consentDate',
      path: '/',
      priority: 'Medium',
      secure: true,
      size: 35,
      value: '2025-04-17T08:35:09.641Z',
      samesite: 'none',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Unknown',
      category: 'Uncategorized',
      name: '',
      domain: '',
      description: '',
      retention: '',
      dataController: '',
      gdprUrl: '',
      wildcard: '',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-04-17T08:35:14.000Z',
      httponly: false,
      name: '_sharedid',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 45,
      value: 'df5bc107-04e7-4bf1-99aa-2e2f1b3ac6bb',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Marfeel',
      category: 'Analytics',
      name: '_s*',
      domain: 'events.newsroom.bi',
      description: 'OCD__s__description',
      retention: 'OCD_retention_Session',
      dataController: 'Marfeel',
      gdprUrl:
        'https://community.marfeel.com/t/marfeel-com-privacy-policy/10383',
      wildcard: '1',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-04-17T08:35:14.000Z',
      httponly: false,
      name: '_sharedid_cst',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 29,
      value: 'SCyvLJQsFA%3D%3D',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Marfeel',
      category: 'Analytics',
      name: '_s*',
      domain: 'events.newsroom.bi',
      description: 'OCD__s__description',
      retention: 'OCD_retention_Session',
      dataController: 'Marfeel',
      gdprUrl:
        'https://community.marfeel.com/t/marfeel-com-privacy-policy/10383',
      wildcard: '1',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: 'national-geographic.pl',
      expires: '2027-04-17T08:35:46.754Z',
      httponly: true,
      name: 'FPID',
      path: '/',
      priority: 'Medium',
      secure: true,
      size: 73,
      value:
        'FPID2.2.VrRcaEeOOS95nJlvb0wysrZjw%2Bh2sxkvV0aPO6V%2BdDQ%3D.1744878908',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Google Analytics',
      category: 'Analytics',
      name: 'FPID',
      domain: '',
      description: 'OCD_FPID_description',
      retention: 'OCD_retention_session',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2025-04-18T04:35:09.737Z',
      httponly: false,
      name: 'FPLC',
      path: '/',
      priority: 'Medium',
      secure: true,
      size: 148,
      value:
        'gfvI8sp0GBNonsYG%2Fnxdf%2Fv9KU5DKrOY6h%2FEzqndcoUFm0E4%2B6KIALB%2Fs1uytIpQnhW3ZaQlZr08FGa%2FicOvYsNXPY4qOU4vWVGAYlrHSyPhSO5THEhPMFHMgFDaDQ%3D%3D',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Google Analytics',
      category: 'Analytics',
      name: 'FPLC',
      domain: '',
      description: 'OCD_FPLC_description',
      retention: 'OCD_retention_session',
      dataController: 'Google',
      gdprUrl: 'https://business.safety.google/privacy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2026-01-12T08:35:10.000Z',
      httponly: false,
      name: '_cc_id',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 38,
      value: '33c4bad9cdb31c4b9c9f52acbfc44cda',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Lotame',
      category: 'Marketing',
      name: '_cc_id',
      domain: 'crwdcntrl.net',
      description: 'OCD__cc_id_description',
      retention: 'OCD_retention_269_days',
      dataController: 'Lotame',
      gdprUrl:
        'https://www.lotame.com/about-lotame/privacy/lotames-products-services-privacy-policy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
  {
    isBlocked: false,
    parsedCookie: {
      domain: '.national-geographic.pl',
      expires: '2025-04-18T08:35:11.000Z',
      httponly: false,
      name: 'panoramaId_expiry',
      path: '/',
      priority: 'Medium',
      secure: false,
      size: 30,
      value: '1744965310180',
      samesite: 'lax',
      partitionKey: '',
    },
    networkEvents: {
      requestEvents: [],
      responseEvents: [],
    },
    blockedReasons: [],
    analytics: {
      platform: 'Lotame',
      category: 'Marketing',
      name: 'panoramaId_expiry',
      domain: '',
      description: 'OCD_panoramaId_expiry_description',
      retention: 'OCD_retention_session',
      dataController: 'Lotame',
      gdprUrl:
        'https://www.lotame.com/about-lotame/privacy/lotames-products-services-privacy-policy/',
      wildcard: '0',
    },
    url: '',
    headerType: 'http',
    isFirstParty: true,
    frameIdList: ['87861506DC8EBE88380B03936A41F211'],
    blockingStatus: {
      inboundBlock: BLOCK_STATUS.NOT_BLOCKED,
      outboundBlock: BLOCK_STATUS.NOT_BLOCKED,
    },
    warningReasons: [],
    isDomainInAllowList: false,
  },
];
