/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { defineConfig } from 'wxt';
import { mergeConfig } from 'vite';
// eslint-disable-next-line import/no-relative-packages
import baseConfig from '../../vite.shared.config.mjs';

export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  entrypointsDir: 'view',
  webExt: {
    // uncomment to disable opening browser
    // disabled: true,
    startUrls: ['https://example.com/?psat_cdp=on&psat_multitab=on'],
    chromiumArgs: [
      `--install-autogenerated-theme='255,51,51'`,
      '--test-third-party-cookie-phaseout',
      `--enable-features="
        FirstPartySets,
        StorageAccessAPI,
        StorageAccessAPIForOriginExtension,
        PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI,
        TpcdMetadataGrants,
        TpcdSupportSettings,
        TpcdHeuristicsGrants:
          TpcdReadHeuristicsGrants/true/TpcdWritePopupCurrentInteractionHeuristicsGrants/30d/TpcdBackfillPopupHeuristicsGrants/30d/TpcdPopupHeuristicEnableForIframeInitiator/all/TpcdWriteRedirectHeuristicGrants/15m/TpcdRedirectHeuristicRequireABAFlow/true/TpcdRedirectHeuristicRequireCurrentInteraction/true`,
    ],
  },
  vite: () =>
    mergeConfig(baseConfig, {
      define: {
        'process.env.IS_RUNNING_STANDALONE': JSON.stringify(true),
      },
    }),
  srcDir: 'src',
  outDir: '../../dist',
  manifestVersion: 3,
  manifest: {
    manifest_version: 3,
    background: {
      service_worker: 'background/background.js',
    },
    name: 'Privacy Sandbox Analysis Tool',
    description:
      'Tooling for understanding cookie usage and guidance on new privacy-preserving Chrome APIs.',
    version: '0.14.1',
    default_locale: 'en',
    icons: {
      '16': 'icons/icon-16.png',
      '32': 'icons/icon-32.png',
      '48': 'icons/icon-48.png',
      '128': 'icons/icon-128.png',
    },
    permissions: [
      'storage',
      'tabs',
      'webNavigation',
      'webRequest',
      'cookies',
      'debugger',
      'management',
      'contentSettings',
      'scripting',
    ],
    web_accessible_resources: [
      {
        resources: [
          'assets/data/*.json',
          'data/*json',
          'report/index.html',
          'content-scripts/prebid-interface.js',
        ],
        matches: ['*://*/*'],
      },
    ],
  },
});
